version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/fluxdown.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: fluxdown-server

build:
  toolchains: []
  run_buildscript: false

images:
  - id: fluxdown-server
    target: service
    service: fluxdown-server
    source: ghcr.io/zerx-lab/fluxdown-server
    channel: stable
    delivery:
      mode: mirror
      image_template: ghcr.1ms.run/zerx-lab/fluxdown-server:{tag}
      require_digest_match: true

stores:
  official:
    enabled: false
  private:
    enabled: true
    skip_if_version_exists: true
    name: FluxDown
    summary: "FluxDown LazyCat LPK release"
